# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Tour
  #   url: tour
  #   weight: 10
  - name: News
    url: /#news
    weight: 20
  - name: People
    url: /#cta
    weight: 30
    #- name: Events
    #  url: event
    #  weight: 40
  - name: Publications
    url: /#welcome
    weight: 10
  - name: Contact
    url: /#contact
    weight: 60
  - name:
    pre: <i class='fa-duotone fa-rss'></i>
    url: index.xml
    weight: 70
